# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u9200/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/huawei/u9200/proprietary/bin/glgps:system/bin/glgps \
    vendor/huawei/u9200/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/huawei/u9200/proprietary/bin/rild:system/bin/rild \
    vendor/huawei/u9200/proprietary/bin/cust:system/bin/cust \
    vendor/huawei/u9200/proprietary/bin/gpslogd:system/bin/gpslogd \
	vendor/huawei/u9200/proprietary/bin/hci_dev_state:system/bin/hci_dev_state \
    vendor/huawei/u9200/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/huawei/u9200/proprietary/vendor/bin/pvrsrvinit:system/vendor/bin/pvrsrvinit \
    vendor/huawei/u9200/proprietary/vendor/bin/pvrsrvctl_SGX540_120:system/vendor/bin/pvrsrvctl_SGX540_120 \
    vendor/huawei/u9200/proprietary/vendor/bin/pvrsrvctl_SGX544_112:system/vendor/bin/pvrsrvctl_SGX544_112 \
    vendor/huawei/u9200/proprietary/vendor/firmware/ducati-m3.bin:system/vendor/firmware/ducati-m3.bin \
    vendor/huawei/u9200/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:system/vendor/firmware/fw_bcmdhd_apsta.bin \
    vendor/huawei/u9200/proprietary/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
    vendor/huawei/u9200/proprietary/vendor/firmware/fw_bcmdhd_p2p.bin:system/vendor/firmware/fw_bcmdhd_p2p.bin \
    vendor/huawei/u9200/proprietary/vendor/firmware/fw_bcmdhd_test.bin:system/vendor/firmware/fw_bcmdhd_test.bin \
    vendor/huawei/u9200/proprietary/vendor/firmware/ducati-m3.bin:system/vendor/firmware/ducati-m3.bin \
	vendor/huawei/u9200/proprietary/vendor/firmware/nvram.txt:system/vendor/firmware/nvram.txt \
    vendor/huawei/u9200/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
    vendor/huawei/u9200/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX544_112.so:system/vendor/lib/egl/libEGL_POWERVR_SGX544_112.so \
    vendor/huawei/u9200/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
    vendor/huawei/u9200/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_112.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_112.so \
    vendor/huawei/u9200/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
    vendor/huawei/u9200/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX544_112.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_112.so \
    vendor/huawei/u9200/proprietary/vendor/lib/hw/gralloc.omap4430.so:system/vendor/lib/hw/gralloc.omap4430.so \
    vendor/huawei/u9200/proprietary/vendor/lib/hw/gralloc.omap4460.so:system/vendor/lib/hw/gralloc.omap4460.so \
    vendor/huawei/u9200/proprietary/vendor/lib/hw/gralloc.omap4470.so:system/vendor/lib/hw/gralloc.omap4470.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libbltsville_cpu.so:system/vendor/lib/libbltsville_cpu.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libbltsville_gc2d.2.1.2.0.so:system/vendor/lib/libbltsville_gc2d.2.1.2.0.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libbltsville_gc2d.so:system/vendor/lib/libbltsville_gc2d.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libbltsville_hw2d.so:system/vendor/lib/libbltsville_hw2d.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libbltsville_ticpu.2.1.0.0.so:system/vendor/lib/libbltsville_ticpu.2.1.0.0.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libbltsville_ticpu_license.txt:system/vendor/lib/libbltsville_ticpu_license.txt \
    vendor/huawei/u9200/proprietary/vendor/lib/libbltsville_ticpu.so:system/vendor/lib/libbltsville_ticpu.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libglslcompiler_SGX540_120.so:system/vendor/lib/libglslcompiler_SGX540_120.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libglslcompiler_SGX544_112.so:system/vendor/lib/libglslcompiler_SGX544_112.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libIMGegl_SGX540_120.so:system/vendor/lib/libIMGegl_SGX540_120.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libIMGegl_SGX544_112.so:system/vendor/lib/libIMGegl_SGX544_112.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libpvr2d_SGX540_120.so:system/vendor/lib/libpvr2d_SGX540_120.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libpvr2d_SGX544_112.so:system/vendor/lib/libpvr2d_SGX544_112.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so:system/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libpvrANDROID_WSEGL_SGX544_112.so:system/vendor/lib/libpvrANDROID_WSEGL_SGX544_112.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libPVRScopeServices_SGX540_120.so:system/vendor/lib/libPVRScopeServices_SGX540_120.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libPVRScopeServices_SGX544_112.so:system/vendor/lib/libPVRScopeServices_SGX544_112.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libsrv_init_SGX540_120.so:system/vendor/lib/libsrv_init_SGX540_120.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libsrv_init_SGX544_112.so:system/vendor/lib/libsrv_init_SGX544_112.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libsrv_um_SGX540_120.so:system/vendor/lib/libsrv_um_SGX540_120.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libsrv_um_SGX544_112.so:system/vendor/lib/libsrv_um_SGX544_112.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libusc_SGX540_120.so:system/vendor/lib/libusc_SGX540_120.so \
    vendor/huawei/u9200/proprietary/vendor/lib/libusc_SGX544_112.so:system/vendor/lib/libusc_SGX544_112.so \
    vendor/huawei/u9200/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/huawei/u9200/proprietary/lib/hw/audio.hdmi.omap4.so:system/lib/hw/audio.hdmi.omap4.so \
    vendor/huawei/u9200/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/huawei/u9200/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/huawei/u9200/proprietary/lib/hw/audio.primary.omap4.so:system/lib/hw/audio.primary.omap4.so \
    vendor/huawei/u9200/proprietary/lib/hw/camera.omap4.so:system/lib/hw/camera.omap4.so \
    vendor/huawei/u9200/proprietary/lib/hw/gps.omap4.so:system/lib/hw/gps.omap4.so \
    vendor/huawei/u9200/proprietary/lib/hw/lights.omap4.so:system/lib/hw/lights.omap4.so \
    vendor/huawei/u9200/proprietary/lib/hw/sensors.omap4.so:system/lib/hw/sensors.omap4.so \
    vendor/huawei/u9200/proprietary/lib/modules/pvrsrvkm_sgx540_120.ko:system/lib/modules/pvrsrvkm_sgx540_120.ko \
    vendor/huawei/u9200/proprietary/lib/modules/pvrsrvkm_sgx544_112.ko:system/lib/modules/pvrsrvkm_sgx544_112.ko \
    vendor/huawei/u9200/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/huawei/u9200/proprietary/lib/libtiutils.so:system/lib/libtiutils.so \
    vendor/huawei/u9200/proprietary/lib/libbluedroid.so:system/lib/libbluedroid.so \
    vendor/huawei/u9200/proprietary/lib/libchip_management.so:system/lib/libchip_management.so \
    vendor/huawei/u9200/proprietary/lib/libdomx.so:system/lib/libdomx.so \
    vendor/huawei/u9200/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/huawei/u9200/proprietary/lib/libmm_osal.so:system/lib/libmm_osal.so \
    vendor/huawei/u9200/proprietary/lib/libOMX_Core.so:system/lib/libOMX_Core.so \
    vendor/huawei/u9200/proprietary/lib/libOMX.TI.DUCATI1.MISC.SAMPLE.so:system/lib/libOMX.TI.DUCATI1.MISC.SAMPLE.so \
    vendor/huawei/u9200/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.CAMERA.so:system/lib/libOMX.TI.DUCATI1.VIDEO.CAMERA.so \
    vendor/huawei/u9200/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.secure.so:system/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.secure.so \
    vendor/huawei/u9200/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.so:system/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.so \
    vendor/huawei/u9200/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.H264E.so:system/lib/libOMX.TI.DUCATI1.VIDEO.H264E.so \
    vendor/huawei/u9200/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4E.so:system/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4E.so \
    vendor/huawei/u9200/proprietary/lib/libparseprofile.so:system/lib/libparseprofile.so \
    vendor/huawei/u9200/proprietary/lib/libRedEye.so:system/lib/libRedEye.so \
    vendor/huawei/u9200/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/huawei/u9200/proprietary/lib/libxgold-ril.so:system/lib/libxgold-ril.so \
    vendor/huawei/u9200/proprietary/etc/firmware/fmc_ch8_1283.2.bts:system/etc/firmware/fmc_ch8_1283.2.bts \
    vendor/huawei/u9200/proprietary/etc/firmware/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
    vendor/huawei/u9200/proprietary/etc/firmware/fm_rx_ch8_1283.2.bts:system/etc/firmware/fm_rx_ch8_1283.2.bts \
    vendor/huawei/u9200/proprietary/etc/firmware/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
    vendor/huawei/u9200/proprietary/etc/firmware/fm_tx_ch8_1273.1.bts:system/etc/firmware/fm_tx_ch8_1273.1.bts \
    vendor/huawei/u9200/proprietary/etc/firmware/fm_tx_ch8_1273.2.bts:system/etc/firmware/fm_tx_ch8_1273.2.bts \
    vendor/huawei/u9200/proprietary/etc/firmware/fm_tx_ch8_1283.2.bts:system/etc/firmware/fm_tx_ch8_1283.2.bts \
    vendor/huawei/u9200/proprietary/etc/firmware/fm_tx_init_1273.2.bts:system/etc/firmware/fm_tx_init_1273.2.bts \
    vendor/huawei/u9200/proprietary/etc/firmware/TIInit_10.6.15.bts:system/etc/firmware/TIInit_10.6.15.bts \
    vendor/huawei/u9200/proprietary/etc/firmware/TIInit_7.2.31.bts:system/etc/firmware/TIInit_7.2.31.bts \
    vendor/huawei/u9200/proprietary/etc/firmware/TIInit_7.6.15.bts:system/etc/firmware/TIInit_7.6.15.bts \
    vendor/huawei/u9200/proprietary/etc/bluetooth/BCM4330B1.hcd:system/etc/bluetooth/BCM4330B1.hcd
